"""add raw json

Revision ID: a381f72a2a01
Revises: d2cbc0b5b6c0
Create Date: 2025-12-22 19:56:36.807171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a381f72a2a01'
down_revision: Union[str, Sequence[str], None] = 'd2cbc0b5b6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('raw_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'raw_json')
    # ### end Alembic commands ###
