"""init schema

Revision ID: d2cbc0b5b6c0
Revises: 
Create Date: 2025-12-21 12:00:31.147766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cbc0b5b6c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('subreddit', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_content_source_id')
    )
    op.create_index('ix_content_items_created_utc', 'content_items', ['created_utc'], unique=False)
    op.create_index('ix_content_items_subreddit', 'content_items', ['subreddit'], unique=False)
    op.create_table('pois',
    sa.Column('poi_id', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('poi_id')
    )
    op.create_table('base_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_name', sa.String(length=128), nullable=False),
    sa.Column('poi_id', sa.String(length=160), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.poi_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_name', 'poi_id', name='uq_base_poi')
    )
    op.create_index(op.f('ix_base_assignments_base_name'), 'base_assignments', ['base_name'], unique=False)
    op.create_index(op.f('ix_base_assignments_poi_id'), 'base_assignments', ['poi_id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('place_mentions', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'summary', name='uq_exp_content_summary')
    )
    op.create_index(op.f('ix_experiences_content_item_id'), 'experiences', ['content_item_id'], unique=False)
    op.create_table('experience_pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('poi_id', sa.String(length=160), nullable=False),
    sa.Column('mention_text', sa.String(length=256), nullable=False),
    sa.Column('link_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.poi_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'poi_id', 'mention_text', name='uq_exp_poi_mention')
    )
    op.create_index(op.f('ix_experience_pois_experience_id'), 'experience_pois', ['experience_id'], unique=False)
    op.create_index(op.f('ix_experience_pois_poi_id'), 'experience_pois', ['poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experience_pois_poi_id'), table_name='experience_pois')
    op.drop_index(op.f('ix_experience_pois_experience_id'), table_name='experience_pois')
    op.drop_table('experience_pois')
    op.drop_index(op.f('ix_experiences_content_item_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_base_assignments_poi_id'), table_name='base_assignments')
    op.drop_index(op.f('ix_base_assignments_base_name'), table_name='base_assignments')
    op.drop_table('base_assignments')
    op.drop_table('pois')
    op.drop_index('ix_content_items_subreddit', table_name='content_items')
    op.drop_index('ix_content_items_created_utc', table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
